package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBank<M extends BaseBank<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}
	
	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public void setParBankId(java.lang.Integer parBankId) {
		set("parBankId", parBankId);
	}
	
	public java.lang.Integer getParBankId() {
		return getInt("parBankId");
	}

	public void setParBankName(java.lang.String parBankName) {
		set("parBankName", parBankName);
	}
	
	public java.lang.String getParBankName() {
		return getStr("parBankName");
	}

}
