package com.fancye.rice.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setParMenuId(java.lang.Integer parMenuId) {
		set("parMenuId", parMenuId);
	}
	
	public java.lang.Integer getParMenuId() {
		return getInt("parMenuId");
	}

	public void setParMenuName(java.lang.String parMenuName) {
		set("parMenuName", parMenuName);
	}
	
	public java.lang.String getParMenuName() {
		return getStr("parMenuName");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
