package com.fancye.rice.common.model;

import com.jfinal.club.common.model.base.BaseAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Account extends BaseAccount<Account> {
	
}
