package com.fancye.rice.common.model;

import com.fancye.rice.common.model.base.BaseBank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bank extends BaseBank<Bank> {
	public static final Bank dao = new Bank().dao();
}
